apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - configs-secrets.yaml
  - postgres.yaml
  - redis.yaml
  - vote.yaml
  - worker.yaml
  - result.yaml

commonLabels:
  project: roxs-voting-app

images:
  - name: vote-image
    newName: ghcr.io/GITHUB_USER/roxs-devops-project90-vote
    newTag: latest
  - name: worker-image
    newName: ghcr.io/GITHUB_USER/roxs-devops-project90-worker
    newTag: latest
  - name: result-image
    newName: ghcr.io/GITHUB_USER/roxs-devops-project90-result
    newTag: latest
