---
apiVersion: v1
kind: Namespace
metadata:
  name: voting-app
  labels:
    name: voting-app
    monitoring: "true"
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/part-of: roxs-devops
